# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

stages:
- stage: Build
  jobs: 
  - job: Build

    pool:
      vmImage: 'vs2017-win2016'

    variables: 
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      

    steps:
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'      
    - task: VSBuild@1
      inputs: 
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    
- stage: Deploy
  jobs: 
  - deployment: DeployARMTemplate
    displayName: Deploy ARM Template
    pool:
      vmImage: 'vs2017-win2016'
    environment: 'testYAML-dev'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureResourceManagerTemplateDeployment@3
              inputs:
                deploymentScope: 'Resource Group'
                azureResourceManagerConnection: 'TestYAML'
                subscriptionId: '91d5a083-c93b-4df9-b783-478aab256259'
                action: 'Create Or Update Resource Group'
                resourceGroupName: 'TestYAML'
                location: 'South Central US'
                templateLocation: 'Linked artifact'
                csmFile: 'TestYAML/AzureResourceGroup/azuredeploy.json'
                csmParametersFile: 'TestYAML/AzureResourceGroup/azuredeploy.parameters-dev.json'
                deploymentMode: 'Incremental'            
